/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'zoom-out': '&#xe900;',
            'zoom-in': '&#xe901;',
            'x-out': '&#xe902;',
            'x-out-circle': '&#xe903;',
            'wifi': '&#xe904;',
            'volume-up': '&#xe905;',
            'mute': '&#xe906;',
            'list': '&#xe907;',
            'grid': '&#xe908;',
            'grid-add': '&#xe909;',
            'boards': '&#xe90a;',
            'video': '&#xe90b;',
            'variable-x': '&#xe90c;',
            'users': '&#xe90d;',
            'user': '&#xe90e;',
            'user-remove': '&#xe90f;',
            'user-group': '&#xe910;',
            'user-circle': '&#xe911;',
            'user-add': '&#xe912;',
            'upload': '&#xe913;',
            'truck': '&#xe914;',
            'trend-up': '&#xe915;',
            'trend-down': '&#xe916;',
            'trash': '&#xe917;',
            'translate': '&#xe918;',
            'ticket': '&#xe919;',
            'thumbs-up': '&#xe91a;',
            'thumbs-down': '&#xe91b;',
            'template': '&#xe91d;',
            'tag': '&#xe91e;',
            'table': '&#xe91f;',
            'table-1': '&#xe920;',
            'switch-vertical': '&#xe921;',
            'switch-horizontal': '&#xe922;',
            'support': '&#xe923;',
            'sun': '&#xe924;',
            'stop': '&#xe925;',
            'status-online': '&#xe926;',
            'status-offline': '&#xe927;',
            'star': '&#xe928;',
            'speaker': '&#xe929;',
            'sparkles': '&#xe92a;',
            'sort-descending': '&#xe92b;',
            'sort-ascending': '&#xe92c;',
            'shopping-bag': '&#xe92d;',
            'shield-explamation': '&#xe92e;',
            'shield-check': '&#xe92f;',
            'share': '&#xe930;',
            'server': '&#xe931;',
            'selector-updown': '&#xe932;',
            'search': '&#xe933;',
            'search-circle': '&#xe934;',
            'scissors': '&#xe935;',
            'scale': '&#xe936;',
            'save': '&#xe937;',
            'save-as': '&#xe938;',
            'rss': '&#xe939;',
            'rewind': '&#xe93a;',
            'reply': '&#xe93b;',
            'refresh': '&#xe93c;',
            'receipt-tax': '&#xe93d;',
            'reciept-refund': '&#xe93e;',
            'question-mark-circ': '&#xe93f;',
            'qrcode': '&#xe940;',
            'puzzle': '&#xe941;',
            'printer': '&#xe942;',
            'pres-chart-line': '&#xe943;',
            'pres-chart-bar': '&#xe944;',
            'plus': '&#xe945;',
            'plus-min': '&#xe946;',
            'plus-circle': '&#xe947;',
            'play': '&#xe948;',
            'photo': '&#xe949;',
            'phone': '&#xe94a;',
            'phone-out': '&#xe94b;',
            'phone-missed': '&#xe94c;',
            'phone-in': '&#xe94d;',
            'pencil': '&#xe94e;',
            'pencil-alt': '&#xe94f;',
            'pause': '&#xe950;',
            'paper-clip': '&#xe951;',
            'paper-airplane': '&#xe952;',
            'office-building': '&#xe953;',
            'newspaper': '&#xe954;',
            'music': '&#xe955;',
            'moon': '&#xe956;',
            'minus': '&#xe957;',
            'minus-min': '&#xe958;',
            'minus-circle': '&#xe959;',
            'mic': '&#xe95a;',
            'menu': '&#xe95b;',
            'menu-alt-4': '&#xe95c;',
            'menu-alt-3': '&#xe95d;',
            'menu-alt-2': '&#xe95e;',
            'menu-alt-1': '&#xe95f;',
            'md-library': '&#xe960;',
            'map': '&#xe961;',
            'mail': '&#xe962;',
            'mail-open': '&#xe963;',
            'mail-1': '&#xe964;',
            'logout': '&#xe965;',
            'logout-1': '&#xe966;',
            'lock-2': '&#xe967;',
            'lock': '&#xe968;',
            'location': '&#xe969;',
            'lightning-bolt': '&#xe96b;',
            'light-bulb': '&#xe96c;',
            'key': '&#xe96d;',
            'info-circle': '&#xe96e;',
            'inbox': '&#xe96f;',
            'inbox-in': '&#xe970;',
            'id': '&#xe971;',
            'home': '&#xe973;',
            'heart': '&#xe974;',
            'hashtag': '&#xe975;',
            'hand': '&#xe976;',
            'globe': '&#xe977;',
            'globe-alt': '&#xe978;',
            'gift': '&#xe979;',
            'folder': '&#xe97a;',
            'folder-remove': '&#xe97b;',
            'folder-open': '&#xe97c;',
            'folder-download': '&#xe97d;',
            'folder-add': '&#xe97e;',
            'flag': '&#xe97f;',
            'finger-print': '&#xe981;',
            'filter': '&#xe982;',
            'film': '&#xe983;',
            'fast-forward': '&#xe984;',
            'eye': '&#xe985;',
            'eye-off': '&#xe986;',
            'ext-link': '&#xe987;',
            'exclamation': '&#xe988;',
            'exlamation-circle': '&#xe989;',
            'emoji-sad': '&#xe98a;',
            'emoji-happy': '&#xe98b;',
            'duplicate': '&#xe98c;',
            'download': '&#xe98d;',
            'download-1': '&#xe98e;',
            'dots-vert': '&#xe98f;',
            'dots-horiz': '&#xe990;',
            'dots-circ-horz': '&#xe991;',
            'doc': '&#xe992;',
            'doc-text': '&#xe993;',
            'doc-search': '&#xe994;',
            'doc-report': '&#xe995;',
            'doc-remove': '&#xe996;',
            'doc-dupe': '&#xe997;',
            'doc-download': '&#xe998;',
            'doc-add': '&#xe999;',
            'device-mobile': '&#xe99a;',
            'computer': '&#xe99b;',
            'database': '&#xe99c;',
            'cursor-click': '&#xe99d;',
            'yen': '&#xe99e;',
            'rupee': '&#xe99f;',
            'currency-pound': '&#xe9a0;',
            'euro': '&#xe9a1;',
            'dollar': '&#xe9a2;',
            'banglade': '&#xe9a3;',
            'cub': '&#xe9a4;',
            'cube-trans': '&#xe9a5;',
            'credit-card': '&#xe9a6;',
            'color-swatch': '&#xe9a7;',
            'collection': '&#xe9a8;',
            'settings': '&#xe9a9;',
            'code-symbol': '&#xe9aa;',
            'cloud': '&#xe9ab;',
            'cloud-upload': '&#xe9ac;',
            'cloud-download': '&#xe9ad;',
            'clock': '&#xe9ae;',
            'clipoard-list': '&#xe9af;',
            'clipboard-copy': '&#xe9b0;',
            'clipoard-check': '&#xe9b1;',
            'chip': '&#xe9b2;',
            'chevron-up': '&#xe9b3;',
            'chevron-right': '&#xe9b4;',
            'chevron-left': '&#xe9b5;',
            'chevron-down': '&#xe9b6;',
            'chevron-dbl-up': '&#xe9b7;',
            'chevron-dbl-right': '&#xe9b8;',
            'chevron-dbl-left': '&#xe9b9;',
            'chevron-dbl-down': '&#xe9ba;',
            'check': '&#xe9bb;',
            'check-circle': '&#xe9bc;',
            'chat': '&#xe9bd;',
            'chat-alt': '&#xe9be;',
            'chat-alt-2': '&#xe9bf;',
            'chart-sqr-bar': '&#xe9c0;',
            'chart-pie': '&#xe9c1;',
            'chart-bar': '&#xe9c2;',
            'cash': '&#xe9c3;',
            'camera': '&#xe9c4;',
            'calendar': '&#xe9c5;',
            'cake': '&#xe9c6;',
            'briefcase': '&#xe9c7;',
            'bookmark': '&#xe9c8;',
            'bookmark-alt': '&#xe9c9;',
            'book-open': '&#xe9ca;',
            'bell': '&#xe9cb;',
            'beaker': '&#xe9cc;',
            'ban': '&#xe9cd;',
            'badge-check': '&#xe9ce;',
            'back-space': '&#xe9cf;',
            'at': '&#xe9d0;',
            'arrows-expand': '&#xe9d1;',
            'arrow-up': '&#xe9d2;',
            'arrow-up-min': '&#xe9d3;',
            'arrow-right-min': '&#xe9d4;',
            'arrow-left-min': '&#xe9d5;',
            'arrow-down-min': '&#xe9d6;',
            'arrow-right': '&#xe9d7;',
            'arrow-up-narrow': '&#xe9d8;',
            'arrow-right-narrow': '&#xe9d9;',
            'arrow-left-narrow': '&#xe9da;',
            'arrow-down-narrow': '&#xe9db;',
            'arrow-left': '&#xe9dc;',
            'arrow-down': '&#xe9dd;',
            'arrow-up-circle': '&#xe9de;',
            'arrow-right-circle': '&#xe9df;',
            'arrow-left-circle': '&#xe9e0;',
            'arrow-down-circle': '&#xe9e1;',
            'archive': '&#xe9e2;',
            'annotate': '&#xe9e3;',
            'adjustments': '&#xe9e4;',
            'academic-cap': '&#xe9e5;',
            'spades': '&#xe9e6;',
            'cards': '&#xe9e6;',
            'clubs': '&#xe9e7;',
            'cards2': '&#xe9e7;',
            'diamonds': '&#xe9e8;',
            'cards3': '&#xe9e8;',
            'spinner11': '&#xe9e9;',
            'loading12': '&#xe9e9;',
            'equalizer': '&#xe9ea;',
            'sliders': '&#xe9ea;',
            'equalizer2': '&#xe9eb;',
            'sliders2': '&#xe9eb;',
            'settings-1': '&#xe9ec;',
            'gear': '&#xe9ec;',
            'fire': '&#xe9ed;',
            'flame': '&#xe9ed;',
            'bin': '&#xe9ee;',
            'trashcan': '&#xe9ee;',
            'earth': '&#xe9ef;',
            'globe2': '&#xe9ef;',
            'link': '&#xe9f0;',
            'chain': '&#xe9f0;',
            'attachment': '&#xe9f1;',
            'paperclip': '&#xe9f1;',
            'omega': '&#xea66;',
            'wysiwyg8': '&#xea66;',
            'terminal': '&#xea81;',
            'console': '&#xea81;',
            'youtube': '&#xea9d;',
            'brand21': '&#xea9d;',
            'github': '&#xeab0;',
            'brand40': '&#xeab0;',
            'html': '&#xeae4;',
            'w3c': '&#xeae4;',
            'css': '&#xeae6;',
            'w3c3': '&#xeae6;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/icon-/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
