/* A polyfill for browsers that don't support ligatures. */
/* The script tag referring to this file must be placed before the ending body tag. */

/* To provide support for elements dynamically added, this script adds
   method 'icomoonLiga' to the window object. You can pass element references to this method.
*/
(function () {
    'use strict';
    function supportsProperty(p) {
        var prefixes = ['Webkit', 'Moz', 'O', 'ms'],
            i,
            div = document.createElement('div'),
            ret = p in div.style;
        if (!ret) {
            p = p.charAt(0).toUpperCase() + p.substr(1);
            for (i = 0; i < prefixes.length; i += 1) {
                ret = prefixes[i] + p in div.style;
                if (ret) {
                    break;
                }
            }
        }
        return ret;
    }
    var icons;
    if (!supportsProperty('fontFeatureSettings')) {
        icons = {
            'javascript': '&#xe900;',
            'building-2': '&#xe901;',
            'java': '&#xe902;',
            'javascript-2': '&#xe903;',
            'placeholder': '&#xe904;',
            'zoom-out': '&#xe905;',
            'zoom-in': '&#xe906;',
            'x-circle': '&#xe908;',
            'wifi': '&#xe909;',
            'volume-up': '&#xe90a;',
            'volume-off': '&#xe90b;',
            'view-list': '&#xe90c;',
            'view-grid': '&#xe90d;',
            'view-grid-add': '&#xe90e;',
            'view-boards': '&#xe90f;',
            'video-camera': '&#xe910;',
            'variable': '&#xe911;',
            'users': '&#xe912;',
            'user': '&#xe913;',
            'user-remove': '&#xe914;',
            'user-group': '&#xe915;',
            'user-circle': '&#xe916;',
            'user-add': '&#xe917;',
            'upload': '&#xe918;',
            'truck': '&#xe919;',
            'trending-up': '&#xe91a;',
            'trending-down': '&#xe91b;',
            'trash': '&#xe91c;',
            'translate': '&#xe91d;',
            'ticket': '&#xe91e;',
            'thumbs-up': '&#xe91f;',
            'thumbs': '&#xe920;',
            'template': '&#xe922;',
            'tag': '&#xe923;',
            'table': '&#xe924;',
            'table-2': '&#xe925;',
            'switch-vertical': '&#xe926;',
            'switch-horizontal': '&#xe927;',
            'support': '&#xe928;',
            'sun': '&#xe929;',
            'stop': '&#xe92a;',
            'status-online': '&#xe92b;',
            'status-offline': '&#xe92c;',
            'star': '&#xe92d;',
            'speaker-phone': '&#xe92e;',
            'sparkles': '&#xe92f;',
            'sort-descending': '&#xe930;',
            'sort-ascending': '&#xe931;',
            'shopping-bag': '&#xe932;',
            'shield-exclamation': '&#xe933;',
            'shield-check': '&#xe934;',
            'share': '&#xe935;',
            'server': '&#xe936;',
            'selector': '&#xe937;',
            'search': '&#xe938;',
            'search-circle': '&#xe939;',
            'scissors': '&#xe93a;',
            'scale': '&#xe93b;',
            'save': '&#xe93c;',
            'save-as': '&#xe93d;',
            'rss': '&#xe93e;',
            'rewind': '&#xe93f;',
            'reply': '&#xe940;',
            'refresh': '&#xe941;',
            'receipt-tax': '&#xe942;',
            'receipt-refund': '&#xe943;',
            'question-mark-circle': '&#xe944;',
            'qrcode': '&#xe945;',
            'puzzle': '&#xe946;',
            'printer': '&#xe947;',
            'presentation-chart-line': '&#xe948;',
            'presentation-chart-bar': '&#xe949;',
            'plus': '&#xe94a;',
            'plus-min': '&#xe94b;',
            'plus-circle': '&#xe94c;',
            'play': '&#xe94d;',
            'photo': '&#xe94e;',
            'phone': '&#xe94f;',
            'phone-out': '&#xe950;',
            'phone-missed': '&#xe951;',
            'phone-in': '&#xe952;',
            'pencil': '&#xe953;',
            'pencil-2': '&#xe954;',
            'pause': '&#xe955;',
            'paper-clip': '&#xe956;',
            'paper-airplane': '&#xe957;',
            'building-3': '&#xe958;',
            'newspaper': '&#xe959;',
            'music': '&#xe95a;',
            'moon': '&#xe95b;',
            'minus': '&#xe95c;',
            'minus-min': '&#xe95d;',
            'minus-circle': '&#xe95e;',
            'mic-2': '&#xe95f;',
            'menu': '&#xe960;',
            'menu-2': '&#xe961;',
            'menu-3': '&#xe962;',
            'menu-4': '&#xe963;',
            'menu-5': '&#xe964;',
            'md-library': '&#xe965;',
            'map': '&#xe966;',
            'mail': '&#xe967;',
            'mail-open': '&#xe968;',
            'mail-2': '&#xe969;',
            'logout': '&#xe96a;',
            'logout-2': '&#xe96b;',
            'lock-open': '&#xe96c;',
            'lock-closed': '&#xe96d;',
            'location': '&#xe96e;',
            'lightning-bolt': '&#xe970;',
            'lightbulb': '&#xe971;',
            'key': '&#xe972;',
            'info-circle-alt': '&#xe973;',
            'inbox': '&#xe974;',
            'inbox-in': '&#xe975;',
            'identification': '&#xe976;',
            'icon-currency-dollar': '&#xe977;',
            'home': '&#xe978;',
            'heart': '&#xe979;',
            'hasthag': '&#xe97a;',
            'hand': '&#xe97b;',
            'globe': '&#xe97c;',
            'globe-2': '&#xe97d;',
            'gift': '&#xe97e;',
            'folder': '&#xe97f;',
            'folder-remove': '&#xe980;',
            'folder-open': '&#xe981;',
            'folder-download': '&#xe982;',
            'folder-add': '&#xe983;',
            'flag': '&#xe984;',
            'finger-print': '&#xe986;',
            'filter': '&#xe987;',
            'film': '&#xe988;',
            'fast-forward': '&#xe989;',
            'eye': '&#xe98a;',
            'eye-off': '&#xe98b;',
            'external-link': '&#xe98c;',
            'exlamation-alt': '&#xe98d;',
            'exclamation-circle-alt': '&#xe98e;',
            'emoji-sad': '&#xe98f;',
            'emoji-happy': '&#xe990;',
            'duplicate': '&#xe991;',
            'download': '&#xe992;',
            'download-2': '&#xe993;',
            'dots-vertical': '&#xe994;',
            'dots-horizontal': '&#xe995;',
            'dots-circle-horizontal': '&#xe996;',
            'doc': '&#xe997;',
            'doc-text': '&#xe998;',
            'doc-search': '&#xe999;',
            'doc-report': '&#xe99a;',
            'doc-remove': '&#xe99b;',
            'doc-duplicate': '&#xe99c;',
            'doc-download': '&#xe99d;',
            'doc-add': '&#xe99e;',
            'device-mobile': '&#xe99f;',
            'desktop-computer': '&#xe9a0;',
            'cursor-click': '&#xe9a2;',
            'yen': '&#xe9a3;',
            'rupee': '&#xe9a4;',
            'pound': '&#xe9a5;',
            'euro': '&#xe9a6;',
            'dollar': '&#xe9a7;',
            'bangladeshi': '&#xe9a8;',
            'cube': '&#xe9a9;',
            'cube-trans': '&#xe9aa;',
            'credit-card': '&#xe9ab;',
            'color-swatch': '&#xe9ac;',
            'collection': '&#xe9ad;',
            'settings': '&#xe9ae;',
            'code': '&#xe9af;',
            'cloud': '&#xe9b0;',
            'cloud-upload': '&#xe9b1;',
            'cloud-download': '&#xe9b2;',
            'clock': '&#xe9b3;',
            'clipboard-list': '&#xe9b4;',
            'clipboard-copy': '&#xe9b5;',
            'clipboard-check': '&#xe9b6;',
            'chip': '&#xe9b7;',
            'chevron-up': '&#xe9b8;',
            'chevron-right': '&#xe9b9;',
            'chevron-left': '&#xe9ba;',
            'chevron-down': '&#xe9bb;',
            'chevron-up-dbl': '&#xe9bc;',
            'chevron-right-dbl': '&#xe9be;',
            'chevron-down-dbl': '&#xe9bf;',
            'check': '&#xe9c0;',
            'check-circle': '&#xe9c1;',
            'chat': '&#xe9c2;',
            'chat-2': '&#xe9c3;',
            'chat-3': '&#xe9c4;',
            'chart-square-bar': '&#xe9c5;',
            'chart-pie': '&#xe9c6;',
            'chart-bar': '&#xe9c7;',
            'cash': '&#xe9c8;',
            'briefcase': '&#xe9cc;',
            'bookmark': '&#xe9cd;',
            'bookmark-2': '&#xe9ce;',
            'book-open': '&#xe9cf;',
            'bell': '&#xe9d0;',
            'beaker': '&#xe9d1;',
            'ban': '&#xe9d2;',
            'arrows-expand': '&#xe9d6;',
            'arrow-up': '&#xe9d7;',
            'arrow-up-min': '&#xe9d8;',
            'arrow-right-min': '&#xe9d9;',
            'arrow-left-min': '&#xe9da;',
            'arrow-down-min': '&#xe9db;',
            'arrow-right': '&#xe9dc;',
            'arrow-up-narrow': '&#xe9dd;',
            'arrow-right-narrow': '&#xe9de;',
            'arrow-left-narrow': '&#xe9df;',
            'arrow-down-narrow': '&#xe9e0;',
            'arrow-left': '&#xe9e1;',
            'arrow-down': '&#xe9e2;',
            'arrow-circle-up': '&#xe9e3;',
            'arrow-right-circle': '&#xe9e4;',
            'arrow-left-circle': '&#xe9e5;',
            'arrow-down-circle': '&#xe9f2;',
            'archive': '&#xe9f3;',
            'annotation': '&#xe9f4;',
            'adjustments': '&#xe9f5;',
            'academic-cap': '&#xe9f6;',
            'unity': '&#xe9f7;',
            'snapchat': '&#xe9f8;',
            'playstation': '&#xe9f9;',
            'instagram': '&#xe9fa;',
            'google-play': '&#xe9fb;',
            'facebook': '&#xe9fc;',
            'discord': '&#xe9fd;',
            'chrome': '&#xe9fe;',
            'android-2': '&#xe9ff;',
            'question': '&#xea00;',
            'question-square': '&#xea01;',
            'question-square-2': '&#xea02;',
            'question-octagon': '&#xea03;',
            'question-octagon-2': '&#xea04;',
            'question-max': '&#xea05;',
            'question-rhombus': '&#xea06;',
            'question-rhombus-2': '&#xea07;',
            'question-circle': '&#xea08;',
            'question-circle-2': '&#xea09;',
            'info': '&#xea0a;',
            'info-3': '&#xea0b;',
            'info-3-fill': '&#xea0c;',
            'info-max': '&#xea0d;',
            'info-circle': '&#xea0e;',
            'info-circle-2': '&#xea0f;',
            'exclamation-triangle': '&#xea11;',
            'exclamation-triangle-2': '&#xea12;',
            'exclamation-square': '&#xea13;',
            'exclamation-square-2': '&#xea14;',
            'exclamation-octagon': '&#xea15;',
            'exclamation-octagon-2': '&#xea16;',
            'exclamation-max': '&#xea17;',
            'exclamation-rhombus': '&#xea18;',
            'exclamation-rhombus-2': '&#xea19;',
            'exclamation-circle': '&#xea1a;',
            'exclamation-circle-2': '&#xea1b;',
            'file-yml': '&#xea1c;',
            'file-xml': '&#xea1d;',
            'file-xls': '&#xea1e;',
            'file-xlsx': '&#xea1f;',
            'file-wofff': '&#xea20;',
            'file-wav': '&#xea21;',
            'file-txt': '&#xea22;',
            'file-ttf': '&#xea23;',
            'file-tsx': '&#xea24;',
            'file-tiff': '&#xea25;',
            'file-svg': '&#xea26;',
            'file-sql': '&#xea27;',
            'file-sh': '&#xea28;',
            'file-scss': '&#xea29;',
            'file-sass': '&#xea2a;',
            'file-rb': '&#xea2b;',
            'file-raw': '&#xea2c;',
            'file-py': '&#xea2d;',
            'file-psd': '&#xea2e;',
            'file-pptx': '&#xea2f;',
            'file-ppt': '&#xea30;',
            'file-png': '&#xea31;',
            'file-php': '&#xea32;',
            'file-pdf': '&#xea33;',
            'file-otf': '&#xea34;',
            'file-mp4': '&#xea35;',
            'file-mp3': '&#xea36;',
            'file-mov': '&#xea37;',
            'file-mdx': '&#xea38;',
            'file-md': '&#xea39;',
            'file-m4p': '&#xea3a;',
            'file-key': '&#xea3b;',
            'file-jsx': '&#xea3c;',
            'file-json': '&#xea3d;',
            'file-js': '&#xea3e;',
            'file-jpg': '&#xea3f;',
            'file-java': '&#xea40;',
            'file-html': '&#xea41;',
            'file-heic': '&#xea42;',
            'file-gif': '&#xea43;',
            'file-exe': '&#xea44;',
            'file-docx': '&#xea45;',
            'file-doc': '&#xea46;',
            'file-csv': '&#xea47;',
            'file-css': '&#xea48;',
            'file-cs': '&#xea49;',
            'file-bmp': '&#xea4a;',
            'file-ai': '&#xea4b;',
            'file-aac': '&#xea4c;',
            'flag-2': '&#xf024;',
            'twitter-2': '&#xf081;',
            'twitter': '&#xf099;',
            'building': '&#xf0f7;',
            'flag-3': '&#xf11d;',
            'mute': '&#xf131;',
            'reddit-2': '&#xf1a1;',
            'toggle-off': '&#xf204;',
            'toggle-on': '&#xf205;',
            'battery-100': '&#xf240;',
            'battery-75': '&#xf241;',
            'battery-50': '&#xf242;',
            'battery-25': '&#xf243;',
            'battery-0': '&#xf244;',
            'mouse': '&#xf245;',
            'headphones': '&#xea4d;',
            'spades': '&#xe9e6;',
            'clubs': '&#xe9e7;',
            'diamonds': '&#xe9e8;',
            'keyboard': '&#xea4e;',
            'computer': '&#xea4f;',
            'drive': '&#xea50;',
            'database-2': '&#xea51;',
            'refresh-2': '&#xe9e9;',
            'adjustments-2': '&#xe9ea;',
            'adjustments-2-vert': '&#xe9eb;',
            'settings-2': '&#xe9ec;',
            'aid-kit': '&#xea52;',
            'fire': '&#xe9ed;',
            'trash-2': '&#xe9ee;',
            'globe-3': '&#xea53;',
            'globe-4': '&#xe9ef;',
            'link-2': '&#xe9f0;',
            'attachment': '&#xe9f1;',
            'contrast': '&#xea54;',
            'omega': '&#xea66;',
            'terminal-2': '&#xea81;',
            'amazon': '&#xea87;',
            'google': '&#xea88;',
            'google-drive': '&#xea8f;',
            'spotify': '&#xea94;',
            'youtube': '&#xea9d;',
            'twitch': '&#xea9f;',
            'github': '&#xeab0;',
            'apple': '&#xeabe;',
            'android': '&#xeac0;',
            'windows': '&#xeac2;',
            'reddit': '&#xeac6;',
            'html': '&#xeae4;',
            'css': '&#xeae6;',
          '0': 0
        };
        delete icons['0'];
        window.icomoonLiga = function (els) {
            var classes,
                el,
                i,
                innerHTML,
                key;
            els = els || document.getElementsByTagName('*');
            if (!els.length) {
                els = [els];
            }
            for (i = 0; ; i += 1) {
                el = els[i];
                if (!el) {
                    break;
                }
                classes = el.className;
                if (/ri-/.test(classes)) {
                    innerHTML = el.innerHTML;
                    if (innerHTML && innerHTML.length > 1) {
                        for (key in icons) {
                            if (icons.hasOwnProperty(key)) {
                                innerHTML = innerHTML.replace(new RegExp(key, 'g'), icons[key]);
                            }
                        }
                        el.innerHTML = innerHTML;
                    }
                }
            }
        };
        window.icomoonLiga();
    }
}());
